name: Mise à jour image

on:
  schedule:
    - cron: '5 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Installation Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Installation dépendances
        run: pip install -r requirements.txt

      - name: Génération image
        run: python date_semaine.py

      - name: Commit image
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add date_semaine.png
          git commit -m "Mise à jour automatique" || exit 0
          git push
